export enum CartWarning {
  PRICE_CHANGED = 'PRICE_CHANGED',
  QUANTITY_REDUCED = 'QUANTITY_REDUCED',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
  PRODUCT_UNAVAILABLE = 'PRODUCT_UNAVAILABLE',
}

export const BLOCKING_CART_WARNINGS: readonly CartWarning[] = [
  CartWarning.QUANTITY_REDUCED,
  CartWarning.OUT_OF_STOCK,
  CartWarning.PRODUCT_UNAVAILABLE,
];
